name: build-and-release

on: 
- push

jobs:
  build:
    permissions:
      content: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install libvirt headers
        run: sudo apt-get install -y libvirt-dev

      - name: Build
        run: cargo build --all --release && strip target/release/bigiron-virt && mv target/release/bigiron-virt target/release/bigiron-virt_x86_64-unknown-linux-gnu

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_COMPRESS: gz
          GHR_PATH: target/release/bigiron-virt_x86_64-unknown-linux-gnu
